// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import cache "github.com/ivanovaleksey/resizer/internal/pkg/resizer/cache"
import image "image"
import mock "github.com/stretchr/testify/mock"

// CacheProvider is an autogenerated mock type for the CacheProvider type
type CacheProvider struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *CacheProvider) Get(_a0 cache.Entity) (image.Image, error) {
	ret := _m.Called(_a0)

	var r0 image.Image
	if rf, ok := ret.Get(0).(func(cache.Entity) image.Image); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(cache.Entity) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: _a0, _a1
func (_m *CacheProvider) Set(_a0 cache.Entity, _a1 image.Image) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(cache.Entity, image.Image) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
